<a href="https://colab.research.google.com/github/maazali04/Machine-Learning-Algorithms/blob/main/Logistic_Regression.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Logistic Regression
Logistic regression is a supervised machine learning algorithm used to predict the probability of a categorical outcome (like Yes/No or True/False)

## Perceptron
- Here the Equation of line is Ax + By + C = 0
- IF a point is above it we take that point add 1 to it and then subtract it from the given line, while if a point is below it then we take that point add 1 to it and then add it with the given line.
- In actual Logistic Regression, we do not take that big step at once. We actually use learning rate. so the equation becomes:
coef = coef - $\eta coordinate$

- We convert our line equation according to Ml logic:

$$ W_0 + W_1X_1 + W_2X_2 = 0$$

If we add $X_0$ (equal to 1) to our dataset:
$$ W_0X_0 + W_1X_1 + W_2X_2 = 0$$
$$ \sum_{i=0}^2 W_iX_i = 0 $$

Algorithm (perceptron):
- Pick a random row from the dataset.
- $X_i$ $\in$ N and $\sum$ $W_i X_i \ge 0$:
  - $W_n = W_{old} - \eta X_i$
- $X_i$ $\in$ P and $\sum$ $W_i X_i < 0$:
  - $W_n = W_{old} + \eta X_i$

Simplified Algorithm:
- $W_n = W-0 + \eta (Y_i - \hat Y_i) X_i$
- Here $\hat Y$ is calculated by step function, While SKlern uses Sigmoid function to calculate the it and sklearn logistic regression is more accurate than this one.

## Binomial Logistic Regression


**Sigmoid Function:**
$$\sigma(z) = \frac{1}{1 + e^{-z}}$$

$$z = w_0 + w_1x_1 + w_2x_2 + \dots + w_kx_k$$

so
$$ \hat{y} = \frac{1}{1 + e^{-(w_0 + w_1x_1 + w_2x_2 + \dots + w_kx_k)}}$$

**Derivative of Sigmoid:**
$$\frac{d\sigma(z)}{dz} = \sigma(z)(1 - \sigma(z)) = \hat{y}(1 - \hat{y})$$

**Cost Function**
- We use Binary Cross-Entropy / Log Loss.
$$J = -\frac{1}{n} \sum_{i=1}^{n} \Big[ y_i \log(\hat{y}_i) + (1 - y_i) \log(1 - \hat{y}_i) \Big]$$
Where:
  - $y_i$ is the actual true label (strictly $0$ or $1$).
  - $\hat{y}_i$ is the predicted probability generated by your sigmoid equation.


**Gradient Descent**
$$\frac{\partial J}{\partial w_j} = \frac{\partial J}{\partial \hat{y}} \cdot \frac{\partial \hat{y}}{\partial z} \cdot \frac{\partial z}{\partial w_j}$$

Piece 1: $\frac{\partial J}{\partial \hat{y}}$ (How Cost changes with the Prediction)

$$\frac{\partial J}{\partial \hat{y}} = - \left( \frac{y}{\hat{y}} + \frac{1-y}{1-\hat{y}} \cdot (-1) \right) = - \frac{y}{\hat{y}} + \frac{1-y}{1-\hat{y}}$$Find a common denominator to combine these two fractions into one:$$\frac{\partial J}{\partial \hat{y}} = \frac{-y(1-\hat{y}) + \hat{y}(1-y)}{\hat{y}(1-\hat{y})}$$$$\frac{\partial J}{\partial \hat{y}} = \frac{-y + y\hat{y} + \hat{y} - y\hat{y}}{\hat{y}(1-\hat{y})} = \frac{\hat{y} - y}{\hat{y}(1-\hat{y})}$$

Piece 2: $\frac{\partial \hat{y}}{\partial z}$ (How Prediction changes with the Linear Score)
$$\frac{\partial \hat{y}}{\partial z} = \hat{y}(1 - \hat{y})$$

Piece 3: $\frac{\partial z}{\partial w_j}$ (How Linear Score changes with a specific Weight)

$$\frac{\partial z}{\partial w_j} = x_j$$


Step 4: Multiplying the Chain Rule Pieces Together
$$\frac{\partial J}{\partial w_j} = \text{(Piece 1)} \cdot \text{(Piece 2)} \cdot \text{(Piece 3)}$$$$\frac{\partial J}{\partial w_j} = \left( \frac{\hat{y} - y}{\hat{y}(1-\hat{y})} \right) \cdot \Big( \hat{y}(1 - \hat{y}) \Big) \cdot (x_j)$$
$$\frac{\partial J}{\partial w_j} = (\hat{y} - y) \cdot x_j$$

Step 5: The Final Gradient Descent Update Rule

$$\frac{\partial J}{\partial w_j} = \frac{1}{n} \sum_{i=1}^{n} (\hat{y}_i - y_i)x_{ij}$$To train the model, Gradient Descent runs a loop over many epochs, updating every single weight simultaneously using a set learning rate ($\alpha$):$$w_j = w_j - \alpha \cdot \left[ \frac{1}{n} \sum_{i=1}^{n} (\hat{y}_i - y_i)x_{ij} \right]$$

Where Does the Sigmoid Function Come From?

**Odds of an event**
  - The odds of an event measure the likelihood of it occurring compared to it not occurring.
  - Odds in favor: The ratio of the probability an event will occur to the probability it will not.
  - Odds against: The ratio of the probability an event will not occur to the probability it will.
  - e.g. Consider the same die roll of a 6:
    - Probability : 1/6
    - Odds in favor: 1/5
    - Odds against: 5/1

  - You can easily convert a known probability \(P\) to odds using the formula:
  $$(\text{Odds}=\frac{P}{1-P})$$
  Odds can only go from $0$ to $+\infty$. It still doesn't match our linear regression line ($z$), which can go from $-\infty$ to $+\infty$.

  To fix this, mathematicians take the Natural Logarithm of the Odds (called the Log-Odds or Logit):$$\text{Logit}(p) = \ln\left(\frac{p}{1-p}\right)$$
  $$\ln\left(\frac{p}{1-p}\right) = z$$
  $$\frac{p}{1-p} = e^z$$Invert both sides:$$\frac{1-p}{p} = \frac{1}{e^z}$$$$\frac{1}{p} - 1 = e^{-z}$$$$\frac{1}{p} = 1 + e^{-z}$$Flip the fraction one last time to solve for $p$:$$p = \frac{1}{1 + e^{-z}}$$

**Derivation of Log Loss Function**:

Step 1: let's look at the basic rules of probability:
 - The probability of an event happening is $\hat{y}$.
 - Because the total probability must always equal 1, the probability of the event not happening is simply $1 - \hat{y}$.

Step 2: Combining Both Cases into a Single Equation
 $$P = \hat{y}^y \cdot (1 - \hat{y})^{(1-y)}$$
 - If y = 1 then P = $\hat y$
 - If y = 0 then P = $1-\hat y$

Step 3: Looking at the Entire Dataset
 $$\text{Total Success} = P_1 \cdot P_2 \cdot P_3 \dots \cdot P_n$$
 $$\text{Total Success} = \big[\hat{y}_1^{y_1} \cdot (1 - \hat{y}_1)^{(1-y_1)}\big] \times \big[\hat{y}_2^{y_2} \cdot (1 - \hat{y}_2)^{(1-y_2)}\big] \times \dots$$

Step 4: The Log Trick (Turning Multiplication into Addition)

 Multiplying thousands of decimals (like $0.9 \times 0.8 \times 0.75 \dots$) creates an insanely tiny number that will break a computer's memory.

 To fix this, we apply a Natural Logarithm ($\ln$) to our total success chain
 $$\ln(\text{Total Success}) = \sum_{i=1}^{n} \ln\big(\hat{y}_i^{y_i} \cdot (1 - \hat{y}_i)^{(1-y_i)}\big)$$

 $$\ln(\text{Total Success}) = \sum_{i=1}^{n} \Big[ y_i \ln(\hat{y}_i) + (1 - y_i) \ln(1 - \hat{y}_i) \Big]$$


 Step 5: Turning it into a Loss Function

 $$J = -\frac{1}{n} \sum_{i=1}^{n} \Big[ y_i \ln(\hat{y}_i) + (1 - y_i) \ln(1 - \hat{y}_i) \Big]$$

**Generalizing the Math for the Whole Dataset (Matrix Form)**

$$\mathbf{z} = \mathbf{X}\mathbf{w} \quad \text{(Shape: } n \times 1\text{)}$$

$$\mathbf{\hat{y}} = \sigma(\mathbf{z}) = \frac{1}{1 + e^{-\mathbf{X}\mathbf{w}}} \quad \text{(Shape: } n \times 1\text{)}$$

$$\frac{\partial J}{\partial \mathbf{w}} = \frac{1}{n} \mathbf{X}^T (\mathbf{\hat{y}} - \mathbf{y})$$

$$\mathbf{w} = \mathbf{w} - \alpha \cdot \left[ \frac{1}{n} \mathbf{X}^T (\mathbf{\hat{y}} - \mathbf{y}) \right]$$

### SKlearn

In [ ]:
import numpy as np
import matplotlib.pyplot as plt
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, classification_report
from sklearn.model_selection import train_test_split
import pandas as pd

In [ ]:
data = pd.read_csv("https://raw.githubusercontent.com/Donges-Niklas/Classification-Titanic-Dataset/master/train.csv")
data.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [ ]:
data= data.drop(["PassengerId","Name","Ticket","Cabin"], axis=1)
data

     Survived  Pclass     Sex   Age  SibSp  Parch     Fare Embarked
0           0       3    male  22.0      1      0   7.2500        S
1           1       1  female  38.0      1      0  71.2833        C
2           1       3  female  26.0      0      0   7.9250        S
3           1       1  female  35.0      1      0  53.1000        S
4           0       3    male  35.0      0      0   8.0500        S
..        ...     ...     ...   ...    ...    ...      ...      ...
886         0       2    male  27.0      0      0  13.0000        S
887         1       1  female  19.0      0      0  30.0000        S
888         0       3  female   NaN      1      2  23.4500        S
889         1       1    male  26.0      0      0  30.0000        C
890         0       3    male  32.0      0      0   7.7500        Q

[891 rows x 8 columns]

In [ ]:
from sklearn.preprocessing import OneHotEncoder, StandardScaler
from sklearn.compose import ColumnTransformer

encoder = OneHotEncoder(sparse_output=False)
scaler = StandardScaler()
preprocessor = ColumnTransformer(
    transformers=[
        ('cat', OneHotEncoder(sparse_output=False), ['Sex',"Embarked"]),
        ('num', StandardScaler(), ['Pclass', 'Age', 'SibSp', 'Parch', 'Fare'])
    ],
    remainder='passthrough'
)
preprocessor.set_output(transform="pandas")
X_transformed = preprocessor.fit_transform(data)
X_transformed

,cat__Sex_female,cat__Sex_male,cat__Embarked_C,cat__Embarked_Q,cat__Embarked_S,cat__Embarked_nan,num__Pclass,num__Age,num__SibSp,num__Parch,num__Fare,remainder__Survived
0,0.0,1.0,0.0,0.0,1.0,0.0,0.827377,-0.530377,0.432793,-0.473674,-0.502445,0
1,1.0,0.0,1.0,0.0,0.0,0.0,-1.566107,0.571831,0.432793,-0.473674,0.786845,1
2,1.0,0.0,0.0,0.0,1.0,0.0,0.827377,-0.254825,-0.474545,-0.473674,-0.488854,1
3,1.0,0.0,0.0,0.0,1.0,0.0,-1.566107,0.365167,0.432793,-0.473674,0.420730,1
4,0.0,1.0,0.0,0.0,1.0,0.0,0.827377,0.365167,-0.474545,-0.473674,-0.486337,0
...,...,...,...,...,...,...,...,...,...,...,...,...
886,0.0,1.0,0.0,0.0,1.0,0.0,-0.369365,-0.185937,-0.474545,-0.473674,-0.386671,0
887,1.0,0.0,0.0,0.0,1.0,0.0,-1.566107,-0.737041,-0.474545,-0.473674,-0.044381,1
888,1.0,0.0,0.0,0.0,1.0,0.0,0.827377,NaN,0.432793,2.008933,-0.176263,0
889,0.0,1.0,1.0,0.0,0.0,0.0,-1.566107,-0.254825,-0.474545,-0.473674,-0.044381,1
890,0.0,1.0,0.0,1.0,0.0,0.0,0.827377,0.158503,-0.474545,-0.473674,-0.492378,0

In [ ]:
X_transformed.isnull().sum()

cat__Sex_female          0
cat__Sex_male            0
cat__Embarked_C          0
cat__Embarked_Q          0
cat__Embarked_S          0
cat__Embarked_nan        0
num__Pclass              0
num__Age               177
num__SibSp               0
num__Parch               0
num__Fare                0
remainder__Survived      0
dtype: int64

In [ ]:
X_transformed["num__Age"].fillna(X_transformed["num__Age"].mean(), inplace=True)

/tmp/ipykernel_990/3556637179.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  X_transformed["num__Age"].fillna(X_transformed["num__Age"].mean(), inplace=True)

In [ ]:
X = X_transformed.drop("remainder__Survived", axis=1)
y = X_transformed["remainder__Survived"]

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [ ]:
lr = LogisticRegression()
lr.fit(X_train, y_train)
y_pred = lr.predict(X_test)
print(f"Accuracy: {accuracy_score(y_test, y_pred)}")
print(f"Coefficient: {lr.coef_}")
print(f"Intercept: {lr.intercept_}")

Accuracy: 0.8100558659217877
Coefficient: [[ 1.32597142 -1.32345427  0.13653353 -0.0089094  -0.30096083  0.17585385
  -0.79301111 -0.45181987 -0.32692678 -0.09639375  0.1192679 ]]
Intercept: [-0.0393368]

### From Scratch

In [ ]:

class LogisticRegressionFromScratch:
    def __init__(self, learning_rate=0.01, num_iterations=1000):
        self.learning_rate = learning_rate
        self.num_iterations = num_iterations
        self.weights = None
        self.bias = None
        self.loss_history = []

    def _sigmoid(self, z):
        # np.clip prevents overflow/underflow errors in exponential calculation
        z = np.clip(z, -500, 500)
        return 1 / (1 + np.exp(-z))

    def _compute_loss(self, y_true, y_pred, m):
        # Add a tiny epsilon value to avoid log(0) which results in NaN
        epsilon = 1e-15
        y_pred = np.clip(y_pred, epsilon, 1 - epsilon)
        loss = - (1 / m) * np.sum(y_true * np.log(y_pred) + (1 - y_true) * np.log(1 - y_pred))
        return loss

    def fit(self, X, y):
        num_samples, num_features = X.shape


        self.weights = np.zeros(num_features)
        self.bias = 0.0

        for i in range(self.num_iterations):
            linear_model = np.dot(X, self.weights) + self.bias
            y_predicted = self._sigmoid(linear_model)

            loss = self._compute_loss(y, y_predicted, num_samples)
            self.loss_history.append(loss)

            dw = (1 / num_samples) * np.dot(X.T, (y_predicted - y))
            db = (1 / num_samples) * np.sum(y_predicted - y)

            self.weights -= self.learning_rate * dw
            self.bias -= self.learning_rate * db

            if i % (self.num_iterations // 10) == 0:
                print(f"Iteration {i}: Loss = {loss:.4f}")

    def predict_proba(self, X):
        linear_model = np.dot(X, self.weights) + self.bias
        return self._sigmoid(linear_model)

    def predict(self, X, threshold=0.5):
        probabilities = self.predict_proba(X)
        return np.where(probabilities >= threshold, 1, 0)

In [ ]:
scratch_model = LogisticRegressionFromScratch()
scratch_model.fit(X_train, y_train)
y_pred = scratch_model.predict(X_test)
print(f"Accuracy: {accuracy_score(y_test, y_pred)}")
print(f"Coefficient: {scratch_model.weights}")
print(f"Intercept: {scratch_model.bias}")

Iteration 0: Loss = 0.6931
Iteration 100: Loss = 0.6094
Iteration 200: Loss = 0.5675
Iteration 300: Loss = 0.5425
Iteration 400: Loss = 0.5254
Iteration 500: Loss = 0.5126
Iteration 600: Loss = 0.5026
Iteration 700: Loss = 0.4946
Iteration 800: Loss = 0.4880
Iteration 900: Loss = 0.4824
Accuracy: 0.8212290502793296
Coefficient: [ 0.66110327 -0.80360256  0.0752113   0.00230148 -0.22882844  0.00881636
 -0.50463546 -0.23473192 -0.19031864  0.03277048  0.23320567]
Intercept: -0.14249929309589374

### Evaluation Matrix
Confusion matrix
 - TP
 - TN
 - FP
 - FN

Accuracy:
  $$ accuracy = \frac {TP + TN} {TN + TP + FP + FN} $$

Note: whenever you deal with imbalanced datasets, accuracy becomes a misleading metrics.

Type 1 error:
 - FP

Type 2 error:
 - FN


Precision:
 - What proportion of predicted positive is positive?
 $$ Precision = \frac {TP } { TP + FP } $$

Recall:
 - Which proportion of actual positive is correctly classified?
 $$ Recall = \frac {TP } { TP + FN } $$


F1 Score:
 $$ Precision = \frac {2 PR } { P+R } $$

TPR: True Positive Rate
  - Out of all the real targets out there, what percentage did my model successfully catch?
   $$ Recall = \frac {TP } { TP + FN } $$
   TPR is also widely known as Recall or Sensitivity

FPR: False Positive Rate
 - Out of all the innocent or healthy cases, what percentage did my model trigger a false alarm on?
 $$\text{FPR}=\frac{\text{FP}}{\text{TN}+\text{FP}}$$

ROC Curve
  - An ROC Curve stands for Receiver Operating Characteristic Curve.
  - It is a graph that shows how well a binary classification model performs across all possible decision thresholds
  - Y-Axis: True Positive Rate (TPR / Recall) (needs to be 1)
  - X-Axis: False Positive Rate (FPR) (needs to be 0)

AUC:
 - AUC stands for Area Under the Curve. Specifically, it measures the entire two-dimensional area underneath the entire ROC curve from (0,0) to (1,1)

## Multi-Class Logistic Regression

**SoftMax Function**
- Its primary job is to take a vector of raw, unconstrained real numbers (called logits) and squash them into a clean probability distribution where every value is between 0 and 1, and all values sum up to exactly 1.
$$\sigma (z)_{i}=\frac{e^{z_{i}}}{\sum _{j=1}^{K}e^{z_{j}}}$$

 - Derivation:
 The simplest way to turn numbers into fractions that add up to 1 is to divide each number by the total sum of all numbers.$$p_i = \frac{z_i}{z_1 + z_2 + z_3}$$
 But this fails, because in some cases we get -1. -1 probability is illegal in mathematics.

 So to make this strictly greater than zero, we use Exponential Function ($e^z$).
 $$p_i = \frac{e^{z_i}}{e^{z_1} + e^{z_2} + e^{z_3}}$$
 &nbsp;
 Generalized Formula:
$$\sigma (z)_{i}=\frac{e^{z_{i}}}{\sum _{j=1}^{K}e^{z_{j}}}$$


**Loss Function**

$$J = -\frac{1}{n} \sum_{i=1}^{n} \sum_{j=1}^{C} y_{ij} \ln(\hat{y}_{ij})$$

**Step By Step Method**
1. First we calculate z (logits) e.g. $z_{\text{Apple}}=w_{11}x_{1}+w_{12}x_{2}+b_{1}, z_{\text{Banana}}=w_{21}x_{1}+w_{22}x_{2}+b_{2}, z_{\text{Orange}}=w_{31}x_{1}+w_{32}x_{2}+b_{3}$
2. Convert Logits to Probabilities using Softmax
3. Make a Prediction
4. Evaluate the Mistake (Cross-Entropy Loss)
5. Update the Weights (Gradient Descent)

## Polynomial Features in Logistic Regression
- Original Features: $[x_1, x_2]$
- New Engineered Features: $[x_1, x_2, x_1^2, x_2^2, x_1x_2]$

- $z=w_{1}x_{1}+w_{2}x_{2}+w_{3}x_{1}^{2}+w_{4}x_{2}^{2}+w_{5}x_{1}x_{2}+b$
- Furthur steps remains the same